export enum SkillsEnums {
    REACT = 'react',
    NEXT = 'next',
    NEST = 'nest',
    NODE = 'node',
    TYPESCRIPT = 'typescript',
    ORACLE_OBJECT_STORAGE = 'oracleObjectStorage',
    DOCKER = 'docker',
    TYPEORM = 'typeorm',
    ORACLE_DATABASE = 'oracleDb',
    PRISMA = 'prisma',
    POSTGRES = 'postgres',
    EXPRESS = 'express',
    JEST = 'jest',
    UNITY = 'unity',
    C_SHARP = 'cSharp',
    JAVA = 'java',
    JAVASCRIPT = 'javascript',
    REACT_NATIVE = 'reactNative',
    FIREBASE = 'firebase',
    AWS = 'aws',
    EC2 = 'ec2',
    S3 = 's3',
    MONGODB = 'mongodb',
    FLUTTER = 'flutter',
    DART = 'dart',
    GIT = 'git',
    CLOUDFLARE = 'cloudflare',
    TAILWIND = 'tailwind',
    DOTNET = 'dotnet',
    REDIS = 'redis',
    ANDROID = 'android',
}

