import './globals.css'
import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import React from "react";
import Header from "@/app/_components/Header";
import Drawer from "@/app/_components/Header/Drawer";

const inter = Montserrat({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <Header/>
            {/*<Drawer/>*/}
            {children}
        </body>
        </html>
    )
}
